AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - config/initializers/*
    - Guardfile
    - app/helpers/ApplicationHelper
    - spec/spec_helper.rb

Metrics/LineLength:
  Description: 'Limit lines to 110 characters.'
  Max: 110

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
